#!/bin/bash
scrot /tmp/screen.png
#convert /tmp/screen.png -type Grayscale -blur 0x10 /tmp/screen.png
convert /tmp/screen.png -resize 10% /tmp/screen.png
convert /tmp/screen.png -type Grayscale -resize 1000% /tmp/screen.png
[[ -f ~/.config/images/lock.png ]] && convert /tmp/screen.png  ~/.config/images/lock.png -gravity center -composite -matte /tmp/screen.png
i3lock -f -i /tmp/screen.png
