#!/bin/env node
const { exec } = require('child_process');

const cheerio = require('cheerio');
const { fetchUrl } = require('fetch');
const wget = require('node-wget');

const urlBase = 'https://unsplash.com';
const search = process.argv[2] || 'mountain'

fetchUrl(`${urlBase}/search/photos/${search}`, (error, meta, body) => {
  const $ = cheerio.load(body.toString());
  const images = [];
  $('[itemprop="contentUrl"]').each((i, el) => {
    images.push($(el).attr('href'));
  });

  // Choose random image
  const image = images[Math.floor(Math.random()*images.length)];

  wget({
    url: `${urlBase}${image}/download?force=true`,
    dest: '/home/jack/Pictures/wallpaper.jpg'
  }, () => {
    exec('feh --bg-scale ~/Pictures/wallpaper.jpg');
  });
});
